# for GHC-8.0.1
extra-deps:
  - data-stringmap-1.0.1.1
  - json-builder-0.3
resolver: lts-7.15

# for GHC-7.10.3
# extra-deps:
#  - data-stringmap-1.0.1.1
# resolver: lts-6.4

flags: {}
packages:
- '.'
