# for GHC-7.10.3
resolver: lts-5.15
extra-deps:
  - cond-0.4.1.1
  - data-stringmap-1.0.1.1

# for GHC-7.8.4
# resolver: lts-2.22
# extra-deps:
#  - cond-0.4.1.1
#  - data-stringmap-1.0.1.1
#  - json-builder-0.3

flags: {}
packages:
- '.'
