clean:
	find . -type f -name '*.als' -print0 | xargs -0 rm -f
	find . -type f -name '*.cfr.des' -print0 | xargs -0 rm -f
	find . -type f -name '*.xml' -print0 | xargs -0 rm -f
	find . -type f -name '*~' -print0 | xargs -0 rm -f