echo " Generating Clafer Models. "

python SPL_Conqueror_XML_To_Clafer_Translator.py --scaledownby 10 --clear_repeated_base_values ScalablePredictionofNonFunctionalProperties/raw/LinkedList/perFeature/LinkedList.xml  ScalablePredictionofNonFunctionalProperties/raw/LinkedList/perFeature/nfpmodel.xml  > ScalablePredictionofNonFunctionalProperties/clafer_models_obtained_by_transformation/linkedlist.cfr

python SPL_Conqueror_XML_To_Clafer_Translator.py --scaledownby 200 --clear_repeated_base_values ScalablePredictionofNonFunctionalProperties/SPLConqueror/PKJab/modelWithoutInteractions.xml  ScalablePredictionofNonFunctionalProperties/raw/PKJab/nfpmodel.xml  > ScalablePredictionofNonFunctionalProperties/clafer_models_obtained_by_transformation/pkjab.cfr

python SPL_Conqueror_XML_To_Clafer_Translator.py --sclaedownby 1000 --clear_repeated_base_values ScalablePredictionofNonFunctionalProperties/raw/SQLite/perFeature/SQLite.xml  ScalablePredictionofNonFunctionalProperties/raw/SQLite/perFeature/nfpmodel.xml  > ScalablePredictionofNonFunctionalProperties/clafer_models_obtained_by_transformation/sqlite.cfr

python SPL_Conqueror_XML_To_Clafer_Translator.py --clear_repeated_base_values ScalablePredictionofNonFunctionalProperties/raw/Violet/perFeature/violetOhneDepReal.xml ScalablePredictionofNonFunctionalProperties/raw/Violet/perFeature/nfpmodel.xml  > ScalablePredictionofNonFunctionalProperties/clafer_models_obtained_by_transformation/violet.cfr

python SPL_Conqueror_XML_To_Clafer_Translator.py --fabricatebasefeature ScalablePredictionofNonFunctionalProperties/raw/BerkeleyC/perFeature/configurations.xml ScalablePredictionofNonFunctionalProperties/raw/BerkeleyC/perFeature/BerkeleyDbCOhneDerivs.xml ScalablePredictionofNonFunctionalProperties/raw/BerkeleyC/perFeature/nfpmodel.xml > ScalablePredictionofNonFunctionalProperties/clafer_models_obtained_by_transformation/berkeleydb.cfr

echo " Compiling Clafer Models into alloy. "

~/clafer/clafer ScalablePredictionofNonFunctionalProperties/clafer_models_obtained_by_transformation/linkedlist.cfr

~/clafer/clafer ScalablePredictionofNonFunctionalProperties/clafer_models_obtained_by_transformation/pkjab.cfr

~/clafer/clafer ScalablePredictionofNonFunctionalProperties/clafer_models_obtained_by_transformation/sqlite.cfr

~/clafer/clafer ScalablePredictionofNonFunctionalProperties/clafer_models_obtained_by_transformation/violet.cfr

~/clafer/clafer ScalablePredictionofNonFunctionalProperties/clafer_models_obtained_by_transformation/berkeleydb.cfr

echo "Finished Compiling Models into alloy."
