from jsir.IR import *

c0_intNumber = Abstract("c0_intNumber");
c0_name = Abstract("c0_name");
c0_realNumber = Abstract("c0_realNumber");
c0_Person = Abstract("c0_Person");
c0_doubleNumber = Abstract("c0_doubleNumber").extending(c0_realNumber);
c0_intNumber2 = Abstract("c0_intNumber2").extending(c0_realNumber);
c0_intNumber3 = Abstract("c0_intNumber3").extending(c0_doubleNumber);
c0_numberOne = Clafer("c0_numberOne").withCard(1, 1).extending(c0_intNumber);
c0_alice = Clafer("c0_alice").withCard(1, 1).extending(c0_name);
c0_pi = Clafer("c0_pi").withCard(1, 1).extending(c0_realNumber);
c0_piDouble = Clafer("c0_piDouble").withCard(1, 1).extending(c0_realNumber);
c0_piInt = Clafer("c0_piInt").withCard(1, 1).extending(c0_realNumber);
c0_numberTwentyFive = Clafer("c0_numberTwentyFive").withCard(1, 1).extending(c0_doubleNumber);
c0_numberThree = Clafer("c0_numberThree").withCard(1, 1).extending(c0_intNumber2);
c0_numberFour = Clafer("c0_numberFour").withCard(1, 1).extending(c0_intNumber2);
c0_likertScaleVal = Clafer("c0_likertScaleVal").withCard(1, 1);
c0_nonZero = Clafer("c0_nonZero").withCard(1, 1);
c0_likes = c0_Person.addChild("c0_likes").withCard(0, 1);
c0_Alice = Clafer("c0_Alice").withCard(1, 1).extending(c0_Person);
c1_Head = c0_Alice.addChild("c1_Head").withCard(1, 1).extending(c0_Head);
c0_Ella = Clafer("c0_Ella").withCard(1, 1).extending(c0_Person);
c0_h = c0_Ella.addChild("c0_h").withCard(1, 1);
c0_heads = Clafer("c0_heads");
c0_friend = Clafer("c0_friend");
c0_onlyAlice = Clafer("c0_onlyAlice").withCard(1, 1);
c0_exceptElla = Clafer("c0_exceptElla");
c0_intNumber.refToUnique("int");
c0_numberOne.refTo("int");
c0_name.refToUnique(string);
c0_alice.refTo(string);
c0_realNumber.refToUnique(real);
c0_pi.refTo(real);
c0_piDouble.refTo(double);
c0_piInt.refTo("int");
c0_doubleNumber.refToUnique(double);
c0_numberTwentyFive.refTo(double);
c0_intNumber2.refToUnique("int");
c0_numberThree.refTo("int");
c0_intNumber3.refToUnique("int");
c0_numberFour.refTo("int");
c0_likes.refTo(c0_Person);
c0_heads.refToUnique(c0_Head);
c0_Alice.addConstraint(equal(joinRef(join($this(), c0_likes)), glob(c0_Ella)));
c0_Ella.addConstraint(none(join($this(), c0_likes)));
scope({c0_Person:2, c0_intNumber2:2, c0_intNumber3:0, c0_likes:2, c0_realNumber:6});
defaultScope(1);
stringLength(16);
