from jsir.IR import *

c0_I = Clafer("c0_I").withCard(1, 1);
c0_S = Clafer("c0_S").withCard(1, 1);
c0_R = Clafer("c0_R").withCard(1, 1);
c0_D = Clafer("c0_D").withCard(1, 1);
c0_R2 = Clafer("c0_R2").withCard(1, 1);
c0_D2 = Clafer("c0_D2").withCard(1, 1);
c0_R3 = Clafer("c0_R3").withCard(1, 1);
c0_R4 = Clafer("c0_R4").withCard(1, 1);
c0_D3 = Clafer("c0_D3").withCard(1, 1);
c0_R5 = Clafer("c0_R5").withCard(1, 1);
c0_I.refTo("int");
c0_S.refTo(string);
c0_R.refTo(real);
c0_D.refTo(double);
c0_R2.refTo(real);
c0_D2.refTo(double);
c0_R3.refTo(real);
c0_R4.refTo(real);
c0_D3.refTo(double);
c0_R5.refTo(real);
Constraint(implies(some(glob(c0_I)), equal(joinRef(glob(c0_I)), constant(5))));
Constraint(implies(some(glob(c0_S)), equal(joinRef(glob(c0_S)), constant("\"some string\""))));
Constraint(implies(some(glob(c0_R)), equal(joinRef(glob(c0_R)), constant(3.1415))));
Constraint(implies(some(glob(c0_D)), equal(joinRef(glob(c0_D)), constant(120.0))));
Constraint(implies(some(glob(c0_R2)), equal(joinRef(glob(c0_R2)), add(constant(3.1415), constant(6)))));
Constraint(implies(some(glob(c0_D2)), equal(joinRef(glob(c0_D2)), add(constant(314.15), constant(7)))));
Constraint(implies(some(glob(c0_R3)), equal(joinRef(glob(c0_R3)), add(constant(3.1415), constant(6.0)))));
Constraint(implies(some(glob(c0_R4)), equal(joinRef(glob(c0_R4)), constant(8))));
Constraint(implies(some(glob(c0_D3)), equal(joinRef(glob(c0_D3)), constant(9))));
Constraint(implies(some(glob(c0_R5)), equal(joinRef(glob(c0_R5)), constant(3.0))));
defaultScope(1);
stringLength(16);
