module Front.Absclafer where

-- Haskell module generated by the BNF converter


newtype PosInteger = PosInteger ((Int,Int),String) deriving (Eq,Ord,Show)
newtype PosDouble = PosDouble ((Int,Int),String) deriving (Eq,Ord,Show)
newtype PosString = PosString ((Int,Int),String) deriving (Eq,Ord,Show)
newtype PosIdent = PosIdent ((Int,Int),String) deriving (Eq,Ord,Show)
data Module =
   Module [Declaration]
 | PosModule Integer Integer [Declaration]
  deriving (Eq,Ord,Show)

data Declaration =
   EnumDecl PosIdent [EnumId]
 | PosEnumDecl Integer Integer PosIdent [EnumId]
 | ElementDecl Element
 | PosElementDecl Integer Integer Element
  deriving (Eq,Ord,Show)

data Clafer =
   Clafer Abstract GCard PosIdent Super Card Init Elements
 | PosClafer Integer Integer Abstract GCard PosIdent Super Card Init Elements
  deriving (Eq,Ord,Show)

data Constraint =
   Constraint [Exp]
 | PosConstraint Integer Integer [Exp]
  deriving (Eq,Ord,Show)

data SoftConstraint =
   SoftConstraint [Exp]
 | PosSoftConstraint Integer Integer [Exp]
  deriving (Eq,Ord,Show)

data Goal =
   Goal [Exp]
 | PosGoal Integer Integer [Exp]
  deriving (Eq,Ord,Show)

data Abstract =
   AbstractEmpty
 | PosAbstractEmpty Integer Integer
 | Abstract
 | PosAbstract Integer Integer
  deriving (Eq,Ord,Show)

data Elements =
   ElementsEmpty
 | PosElementsEmpty Integer Integer
 | ElementsList [Element]
 | PosElementsList Integer Integer [Element]
  deriving (Eq,Ord,Show)

data Element =
   Subclafer Clafer
 | PosSubclafer Integer Integer Clafer
 | ClaferUse Name Card Elements
 | PosClaferUse Integer Integer Name Card Elements
 | Subconstraint Constraint
 | PosSubconstraint Integer Integer Constraint
 | Subgoal Goal
 | PosSubgoal Integer Integer Goal
 | Subsoftconstraint SoftConstraint
 | PosSubsoftconstraint Integer Integer SoftConstraint
  deriving (Eq,Ord,Show)

data Super =
   SuperEmpty
 | PosSuperEmpty Integer Integer
 | SuperSome SuperHow SetExp
 | PosSuperSome Integer Integer SuperHow SetExp
  deriving (Eq,Ord,Show)

data SuperHow =
   SuperColon
 | PosSuperColon Integer Integer
 | SuperArrow
 | PosSuperArrow Integer Integer
 | SuperMArrow
 | PosSuperMArrow Integer Integer
  deriving (Eq,Ord,Show)

data Init =
   InitEmpty
 | PosInitEmpty Integer Integer
 | InitSome InitHow Exp
 | PosInitSome Integer Integer InitHow Exp
  deriving (Eq,Ord,Show)

data InitHow =
   InitHow_1
 | PosInitHow_1 Integer Integer
 | InitHow_2
 | PosInitHow_2 Integer Integer
  deriving (Eq,Ord,Show)

data GCard =
   GCardEmpty
 | PosGCardEmpty Integer Integer
 | GCardXor
 | PosGCardXor Integer Integer
 | GCardOr
 | PosGCardOr Integer Integer
 | GCardMux
 | PosGCardMux Integer Integer
 | GCardOpt
 | PosGCardOpt Integer Integer
 | GCardInterval NCard
 | PosGCardInterval Integer Integer NCard
  deriving (Eq,Ord,Show)

data Card =
   CardEmpty
 | PosCardEmpty Integer Integer
 | CardLone
 | PosCardLone Integer Integer
 | CardSome
 | PosCardSome Integer Integer
 | CardAny
 | PosCardAny Integer Integer
 | CardNum PosInteger
 | PosCardNum Integer Integer PosInteger
 | CardInterval NCard
 | PosCardInterval Integer Integer NCard
  deriving (Eq,Ord,Show)

data NCard =
   NCard PosInteger ExInteger
 | PosNCard Integer Integer PosInteger ExInteger
  deriving (Eq,Ord,Show)

data ExInteger =
   ExIntegerAst
 | PosExIntegerAst Integer Integer
 | ExIntegerNum PosInteger
 | PosExIntegerNum Integer Integer PosInteger
  deriving (Eq,Ord,Show)

data Name =
   Path [ModId]
 | PosPath Integer Integer [ModId]
  deriving (Eq,Ord,Show)

data Exp =
   DeclAllDisj Decl Exp
 | PosDeclAllDisj Integer Integer Decl Exp
 | DeclAll Decl Exp
 | PosDeclAll Integer Integer Decl Exp
 | DeclQuantDisj Quant Decl Exp
 | PosDeclQuantDisj Integer Integer Quant Decl Exp
 | DeclQuant Quant Decl Exp
 | PosDeclQuant Integer Integer Quant Decl Exp
 | EGMax Exp
 | PosEGMax Integer Integer Exp
 | EGMin Exp
 | PosEGMin Integer Integer Exp
 | EIff Exp Exp
 | PosEIff Integer Integer Exp Exp
 | EImplies Exp Exp
 | PosEImplies Integer Integer Exp Exp
 | EOr Exp Exp
 | PosEOr Integer Integer Exp Exp
 | EXor Exp Exp
 | PosEXor Integer Integer Exp Exp
 | EAnd Exp Exp
 | PosEAnd Integer Integer Exp Exp
 | ENeg Exp
 | PosENeg Integer Integer Exp
 | ELt Exp Exp
 | PosELt Integer Integer Exp Exp
 | EGt Exp Exp
 | PosEGt Integer Integer Exp Exp
 | EEq Exp Exp
 | PosEEq Integer Integer Exp Exp
 | ELte Exp Exp
 | PosELte Integer Integer Exp Exp
 | EGte Exp Exp
 | PosEGte Integer Integer Exp Exp
 | ENeq Exp Exp
 | PosENeq Integer Integer Exp Exp
 | EIn Exp Exp
 | PosEIn Integer Integer Exp Exp
 | ENin Exp Exp
 | PosENin Integer Integer Exp Exp
 | QuantExp Quant Exp
 | PosQuantExp Integer Integer Quant Exp
 | EAdd Exp Exp
 | PosEAdd Integer Integer Exp Exp
 | ESub Exp Exp
 | PosESub Integer Integer Exp Exp
 | EMul Exp Exp
 | PosEMul Integer Integer Exp Exp
 | EDiv Exp Exp
 | PosEDiv Integer Integer Exp Exp
 | ECSetExp Exp
 | PosECSetExp Integer Integer Exp
 | EMinExp Exp
 | PosEMinExp Integer Integer Exp
 | EImpliesElse Exp Exp Exp
 | PosEImpliesElse Integer Integer Exp Exp Exp
 | EInt PosInteger
 | PosEInt Integer Integer PosInteger
 | EDouble PosDouble
 | PosEDouble Integer Integer PosDouble
 | EStr PosString
 | PosEStr Integer Integer PosString
 | ESetExp SetExp
 | PosESetExp Integer Integer SetExp
  deriving (Eq,Ord,Show)

data SetExp =
   Union SetExp SetExp
 | PosUnion Integer Integer SetExp SetExp
 | UnionCom SetExp SetExp
 | PosUnionCom Integer Integer SetExp SetExp
 | Difference SetExp SetExp
 | PosDifference Integer Integer SetExp SetExp
 | Intersection SetExp SetExp
 | PosIntersection Integer Integer SetExp SetExp
 | Domain SetExp SetExp
 | PosDomain Integer Integer SetExp SetExp
 | Range SetExp SetExp
 | PosRange Integer Integer SetExp SetExp
 | Join SetExp SetExp
 | PosJoin Integer Integer SetExp SetExp
 | ClaferId Name
 | PosClaferId Integer Integer Name
  deriving (Eq,Ord,Show)

data Decl =
   Decl [LocId] SetExp
 | PosDecl Integer Integer [LocId] SetExp
  deriving (Eq,Ord,Show)

data Quant =
   QuantNo
 | PosQuantNo Integer Integer
 | QuantLone
 | PosQuantLone Integer Integer
 | QuantOne
 | PosQuantOne Integer Integer
 | QuantSome
 | PosQuantSome Integer Integer
  deriving (Eq,Ord,Show)

data EnumId =
   EnumIdIdent PosIdent
 | PosEnumIdIdent Integer Integer PosIdent
  deriving (Eq,Ord,Show)

data ModId =
   ModIdIdent PosIdent
 | PosModIdIdent Integer Integer PosIdent
  deriving (Eq,Ord,Show)

data LocId =
   LocIdIdent PosIdent
 | PosLocIdIdent Integer Integer PosIdent
  deriving (Eq,Ord,Show)

