module Front.Absclafer where

-- Haskell module generated by the BNF converter

newtype Ident = Ident String deriving (Eq,Ord,Show)
data Module =
   Module [Declaration]
  deriving (Eq,Ord,Show)

data Declaration =
   EnumDecl Ident [EnumId]
 | ClaferDecl Clafer
 | ConstDecl Constraint
  deriving (Eq,Ord,Show)

data Clafer =
   Clafer Abstract GCard Ident Super Card Elements
  deriving (Eq,Ord,Show)

data Constraint =
   Constraint [Exp]
  deriving (Eq,Ord,Show)

data Abstract =
   AbstractEmpty
 | Abstract
  deriving (Eq,Ord,Show)

data Elements =
   ElementsEmpty
 | ElementsList [ElementCl]
  deriving (Eq,Ord,Show)

data ElementCl =
   Subclafer Clafer
 | ClaferUse Name Card Elements
 | Subconstraint Constraint
  deriving (Eq,Ord,Show)

data Super =
   SuperEmpty
 | SuperColon Name
 | SuperExtends Name
 | SuperArrow Exp
  deriving (Eq,Ord,Show)

data GCard =
   GCardEmpty
 | GCardXor
 | GCardOr
 | GCardMux
 | GCardOpt
 | GCardInterval GNCard
  deriving (Eq,Ord,Show)

data Card =
   CardEmpty
 | CardLone
 | CardSome
 | CardAny
 | CardInterval NCard
  deriving (Eq,Ord,Show)

data GNCard =
   GNCard Integer ExInteger
  deriving (Eq,Ord,Show)

data NCard =
   NCard Integer ExInteger
  deriving (Eq,Ord,Show)

data ExInteger =
   ExIntegerAst
 | ExIntegerNum Integer
  deriving (Eq,Ord,Show)

data Name =
   LocClafer Ident
 | ModClafer [ModId] Ident
  deriving (Eq,Ord,Show)

data Exp =
   DeclExp ExQuant [Decl] Exp
 | EIff Exp Exp
 | EImplies Exp Exp
 | EImpliesElse Exp Exp Exp
 | EOr Exp Exp
 | EXor Exp Exp
 | EAnd Exp Exp
 | ENeg Exp
 | QuantExp Quant Exp
 | ELt Exp Exp
 | EGt Exp Exp
 | EEq Exp Exp
 | ELte Exp Exp
 | EGte Exp Exp
 | ENeq Exp Exp
 | EIn Exp Exp
 | ENin Exp Exp
 | EAdd Exp Exp
 | ESub Exp Exp
 | EMul Exp Exp
 | EDiv Exp Exp
 | ECSetExp Exp
 | EInt Integer
 | EDouble Double
 | EStr String
 | Union Exp Exp
 | Difference Exp Exp
 | Intersection Exp Exp
 | Domain Exp Exp
 | Range Exp Exp
 | Join Exp Exp
 | ClaferId Name
  deriving (Eq,Ord,Show)

data Decl =
   Decl Disj [LocId] Exp
  deriving (Eq,Ord,Show)

data Disj =
   DisjEmpty
 | Disj
  deriving (Eq,Ord,Show)

data Quant =
   QuantNo
 | QuantLone
 | QuantOne
 | QuantSome
  deriving (Eq,Ord,Show)

data ExQuant =
   ExQuantAll
 | ExQuantQuant Quant
  deriving (Eq,Ord,Show)

data EnumId =
   EnumIdIdent Ident
  deriving (Eq,Ord,Show)

data ModId =
   ModIdIdent Ident
  deriving (Eq,Ord,Show)

data LocId =
   LocIdIdent Ident
  deriving (Eq,Ord,Show)

